version: '3.5'

services:
  postgres:
    image: 'postgres:13.1-alpine'
    container_name: postgres
    environment:
      - POSTGRES_USER=ase_admin
      - POSTGRES_PASSWORD=#?HY:YCV4nMk
      - POSTGRES_DB=ase
    expose:
      - "5432"
    ports:
      - "5432:5432"